package com.vetador.minescapersmusic;

import java.util.HashMap;
import java.util.Map;

import static com.mojang.text2speech.Narrator.LOGGER;

public class SoundsMap {

    // Static map initialization
    public static final Map<String, String> soundMap = new HashMap<>();

    public static void addSoundToMap(String overlay, String name) {
        soundMap.put(overlay, name);
    }

    public static void initializeSounds() {
        addSoundToMap("Alchemical Attack", "alchemical_attack");
        addSoundToMap("Amascuts Promise", "amascuts_promise");
        addSoundToMap("Ape-ex Predator", "ape_ex_predator");
        addSoundToMap("Arachnids of Vampyrium", "arachnids_of_vampyrium");
        addSoundToMap("Arcane", "arcane");
        addSoundToMap("Architects of Prifddinas", "architects_of_prifddinas");
        addSoundToMap("Ascent", "ascent");
        addSoundToMap("A Dangerous Game", "a_dangerous_game");
        addSoundToMap("A Farmers Grind", "a_farmers_grind");
        addSoundToMap("A Forgotten Religion", "a_forgotten_religion");
        addSoundToMap("A Mothers Curse", "a_mothers_curse");
        addSoundToMap("A Taste of Hope", "a_taste_of_hope");
        addSoundToMap("A Thorn in My Side", "a_thorn_in_my_side");
        addSoundToMap("A Walk in the Woods", "a_walk_in_the_woods");
        addSoundToMap("A Worthy Foe", "a_worthy_foe");
        addSoundToMap("Barren Land", "barren_land");
        addSoundToMap("Beneath Cursed Sands", "beneath_cursed_sands");
        addSoundToMap("Beneath the Kingdom", "beneath_the_kingdom");
        addSoundToMap("Beneath the Stronghold", "beneath_the_stronghold");
        addSoundToMap("Beyond the Meadow", "beyond_the_meadow");
        addSoundToMap("Blood Rush (music track)", "blood_rush_(music_track)");
        addSoundToMap("Box of Delights", "box_of_delights");
        addSoundToMap("Bunnys Sugar Rush", "bunnys_sugar_rush");
        addSoundToMap("Burning Desire", "burning_desire");
        addSoundToMap("Children of the Sun", "children_of_the_sun");
        addSoundToMap("Clanliness", "clanliness");
        addSoundToMap("Coil", "coil");
        addSoundToMap("Colossus of the Deep", "colossus_of_the_deep");
        addSoundToMap("Confrontation", "confrontation");
        addSoundToMap("Country Jig", "country_jig");
        addSoundToMap("Creeping Vines", "creeping_vines");
        addSoundToMap("Dance of the Meilyr", "dance_of_the_meilyr");
        addSoundToMap("Dance of the Nylocas", "dance_of_the_nylocas");
        addSoundToMap("Darkly Altared", "darkly_altared");
        addSoundToMap("Darkness in the Depths", "darkness_in_the_depths");
        addSoundToMap("Devils May Care", "devils_may_care");
        addSoundToMap("Dies Irae", "dies_irae");
        addSoundToMap("Down by the Docks", "down_by_the_docks");
        addSoundToMap("Dunes of Eternity", "dunes_of_eternity");
        addSoundToMap("Dwarven Domain", "dwarven_domain");
        addSoundToMap("Elven Guardians", "elven_guardians");
        addSoundToMap("Eves Epinette", "eves_epinette");
        addSoundToMap("Eye See You", "eye_see_you");
        addSoundToMap("Faith of the Hefin", "faith_of_the_hefin");
        addSoundToMap("Fire in the Deep", "fire_in_the_deep");
        addSoundToMap("Fossilised", "fossilised");
        addSoundToMap("Ful to the Brim", "ful_to_the_brim");
        addSoundToMap("Getting Down to Business", "getting_down_to_business");
        addSoundToMap("Gill Bill", "gill_bill");
        addSoundToMap("Gnome Village Party", "gnome_village_party");
        addSoundToMap("Grow Grow Grow", "grow_grow_grow");
        addSoundToMap("Guardians of the Rift", "guardians_of_the_rift");
        addSoundToMap("Hoe Down", "hoe_down");
        addSoundToMap("Ice and Fire", "ice_and_fire");
        addSoundToMap("Inferno", "inferno");
        addSoundToMap("Into the Tombs", "into_the_tombs");
        addSoundToMap("Invader", "invader");
        addSoundToMap("Its not over til", "its_not_over_til");
        addSoundToMap("Jaws of Gluttony", "jaws_of_gluttony");
        addSoundToMap("Judgement of the Depths", "judgement_of_the_depths");
        addSoundToMap("Kanon of Kahlith", "kanon_of_kahlith");
        addSoundToMap("Kourend the Magnificent", "kourend_the_magnificent");
        addSoundToMap("Lagoon", "lagoon");
        addSoundToMap("Laid to Rest", "laid_to_rest");
        addSoundToMap("Last King of the Yarasa", "last_king_of_the_yarasa");
        addSoundToMap("Last Man Standing", "last_man_standing");
        addSoundToMap("Lava is Mine", "lava_is_mine");
        addSoundToMap("Lower Depths", "lower_depths");
        addSoundToMap("Lucid Dream", "lucid_dream");
        addSoundToMap("Lucid Nightmare", "lucid_nightmare");
        addSoundToMap("Lumbering", "lumbering");
        addSoundToMap("March of the Shayzien", "march_of_the_shayzien");
        addSoundToMap("Master of Puppets", "master_of_puppets");
        addSoundToMap("Maws Jaws & Claws", "maws_jaws_and_claws");
        addSoundToMap("Military Life", "military_life");
        addSoundToMap("Monkey Badness", "monkey_badness");
        addSoundToMap("Monkey Business", "monkey_business");
        addSoundToMap("Monkey Sadness", "monkey_sadness");
        addSoundToMap("Monkey Trouble", "monkey_trouble");
        addSoundToMap("More Than Meets the Eye", "more_than_meets_the_eye");
        addSoundToMap("Mor Ul Rek", "mor_ul_rek");
        addSoundToMap("Mother Ruckus", "mother_ruckus");
        addSoundToMap("Museum Medley", "museum_medley");
        addSoundToMap("Mystics of Nature", "mystics_of_nature");
        addSoundToMap("Mythical", "mythical");
        addSoundToMap("Nether Realm", "nether_realm");
        addSoundToMap("Newbie Farming", "newbie_farming");
        addSoundToMap("Not a Moment of Relief", "not_a_moment_of_relief");
        addSoundToMap("Nox Irae", "nox_irae");
        addSoundToMap("No Pasaran", "no_pasaran");
        addSoundToMap("Oncoming Foe", "oncoming_foe");
        addSoundToMap("On the Frontline", "on_the_frontline");
        addSoundToMap("On the Shore", "on_the_shore");
        addSoundToMap("On Thin Ice", "on_thin_ice");
        addSoundToMap("Out at the Mines", "out_at_the_mines");
        addSoundToMap("Pick & Shovel", "pick_and_shovel");
        addSoundToMap("Plots and Plans", "plots_and_plans");
        addSoundToMap("Power of the Shadow Realm", "power_of_the_shadow_realm");
        addSoundToMap("Predator Xarpus", "predator_xarpus");
        addSoundToMap("Preservation", "preservation");
        addSoundToMap("Preserved", "preserved");
        addSoundToMap("Regal Pomp", "regal_pomp");
        addSoundToMap("Reign of the Basilisk", "reign_of_the_basilisk");
        addSoundToMap("Relics", "relics");
        addSoundToMap("Rest in Peace", "rest_in_peace");
        addSoundToMap("Revenants", "revenants");
        addSoundToMap("Rhapsody", "rhapsody");
        addSoundToMap("Rose", "rose");
        addSoundToMap("Rugged Terrain", "rugged_terrain");
        addSoundToMap("Ruins of Isolation", "ruins_of_isolation");
        addSoundToMap("Sands of Time", "sands_of_time");
        addSoundToMap("Sarachnis", "sarachnis");
        addSoundToMap("Scape Ape", "scape_ape");
        addSoundToMap("Scape Crystal", "scape_crystal");
        addSoundToMap("Scape Five", "scape_five");
        addSoundToMap("Scar Tissue", "scar_tissue");
        addSoundToMap("Scorpia Dances", "scorpia_dances");
        addSoundToMap("Scrubfoots Descent", "scrubfoots_descent");
        addSoundToMap("Sea Minor Shanty", "sea_minor_shanty");
        addSoundToMap("Secrets of the North", "secrets_of_the_north");
        addSoundToMap("Servants of Strife", "servants_of_strife");
        addSoundToMap("Sharp End of the Crystal", "sharp_end_of_the_crystal");
        addSoundToMap("Snowflake & My Arm", "snowflake_and_my_arm");
        addSoundToMap("Song of the Elves", "song_of_the_elves");
        addSoundToMap("Song of the Silent Choir", "song_of_the_silent_choir");
        addSoundToMap("Soul Fall", "soul_fall");
        addSoundToMap("Stand Up and Be Counted", "stand_up_and_be_counted");
        addSoundToMap("Strangled", "strangled");
        addSoundToMap("Stuck in the Mire", "stuck_in_the_mire");
        addSoundToMap("Tempest", "tempest");
        addSoundToMap("Temple of the Eye", "temple_of_the_eye");
        addSoundToMap("Tempor of the Storm", "tempor_of_the_storm");
        addSoundToMap("Test of Companionship", "test_of_companionship");
        addSoundToMap("Test of Isolation", "test_of_isolation");
        addSoundToMap("Test of Resourcefulness", "test_of_resourcefulness");
        addSoundToMap("Test of Strength", "test_of_strength");
        addSoundToMap("That Sullen Hall", "that_sullen_hall");
        addSoundToMap("The Bane of Ashihama", "the_bane_of_ashihama");
        addSoundToMap("The Burning Sun", "the_burning_sun");
        addSoundToMap("The Curtain Closes", "the_curtain_closes");
        addSoundToMap("The Dark Beast Sotetseg", "the_dark_beast_sotetseg");
        addSoundToMap("The Desolate Mage", "the_desolate_mage");
        addSoundToMap("The Doors of Dinh", "the_doors_of_dinh");
        addSoundToMap("The Dragon Slayer", "the_dragon_slayer");
        addSoundToMap("The Everlasting Slumber", "the_everlasting_slumber");
        addSoundToMap("The Fallen Empire", "the_fallen_empire");
        addSoundToMap("The Fat Lady Sings", "the_fat_lady_sings");
        addSoundToMap("The Fires of Lletya", "the_fires_of_lletya");
        addSoundToMap("The Forests of Shayzien", "the_forests_of_shayzien");
        addSoundToMap("The Forgotten Tomb", "the_forgotten_tomb");
        addSoundToMap("The Forlorn Homestead", "the_forlorn_homestead");
        addSoundToMap("The Forsaken", "the_forsaken");
        addSoundToMap("The Forsaken Tower", "the_forsaken_tower");
        addSoundToMap("The Foundry", "the_foundry");
        addSoundToMap("The Fragment", "the_fragment");
        addSoundToMap("The Gauntlet", "the_gauntlet");
        addSoundToMap("The Guardians Prepare", "the_guardians_prepare");
        addSoundToMap("The Houses of Kourend", "the_houses_of_kourend");
        addSoundToMap("The Maidens Anger", "the_maidens_anger");
        addSoundToMap("The Maidens Sorrow", "the_maidens_sorrow");
        addSoundToMap("The Militia", "the_militia");
        addSoundToMap("The Nightmare Continues", "the_nightmare_continues");
        addSoundToMap("The Old Ones", "the_old_ones");
        addSoundToMap("The Part Where You Die", "the_part_where_you_die");
        addSoundToMap("The Pharaoh", "the_pharaoh");
        addSoundToMap("The Seed of Crwys", "the_seed_of_crwys");
        addSoundToMap("The Spurned Demon", "the_spurned_demon");
        addSoundToMap("The Tower of Voices", "the_tower_of_voices");
        addSoundToMap("The Vault", "the_vault");
        addSoundToMap("The Walking Dead", "the_walking_dead");
        addSoundToMap("Thrall of the Devourer", "thrall_of_the_devourer");
        addSoundToMap("Thrall of the Serpent", "thrall_of_the_serpent");
        addSoundToMap("Tick Tock", "tick_tock");
        addSoundToMap("Trahaearn Toil", "trahaearn_toil");
        addSoundToMap("Troll Shuffle", "troll_shuffle");
        addSoundToMap("Troubled Waters", "troubled_waters");
        addSoundToMap("Upper Depths", "upper_depths");
        addSoundToMap("Warpath", "warpath");
        addSoundToMap("Watch Your Step", "watch_your_step");
        addSoundToMap("Way of the Wyrm", "way_of_the_wyrm");
        addSoundToMap("Welcome to my Nightmare", "welcome_to_my_nightmare");
        addSoundToMap("Welcome to the Theatre", "welcome_to_the_theatre");
        addSoundToMap("Well Hallowed Air", "well_hallowed_air");
        addSoundToMap("What Happens Below", "what_happens_below");
        addSoundToMap("You Have My Attention", "you_have_my_attention");


        addSoundToMap("7th Realm", "7th_realm");
        addSoundToMap("A Familiar Feeling", "a_familiar_feeling");
        addSoundToMap("A Handful of Coins", "a_handful_of_coins");
        addSoundToMap("A Little Learning", "a_little_learning");
        addSoundToMap("A Malice Unleashed", "a_malice_unleashed");
        addSoundToMap("A New Menace", "a_new_menace");
        addSoundToMap("A Pirates Life for Me", "a_pirates_life_for_me");
        addSoundToMap("A Purse Full of Silver", "a_purse_full_of_silver");
        addSoundToMap("A Song for Khnum", "a_song_for_khnum");
        addSoundToMap("Abomination", "abomination");
        addSoundToMap("Above the City", "above_the_city");
        addSoundToMap("Abstract of Seren", "abstract_of_seren");
        addSoundToMap("Abstract of Sliske", "abstract_of_sliske");
        addSoundToMap("Abstract of Zamorak", "abstract_of_zamorak");
        addSoundToMap("Abstract of Zaros", "abstract_of_zaros");
        addSoundToMap("Abyssopelagic", "abyssopelagic");
        addSoundToMap("Adagio for Anachronia", "adagio_for_anachronia");
        addSoundToMap("Adorno I", "adorno_i");
        addSoundToMap("Adorno II", "adorno_ii");
        addSoundToMap("Adorno III", "adorno_iii");
        addSoundToMap("Adorno IX", "adorno_ix");
        addSoundToMap("Adorno V", "adorno_v");
        addSoundToMap("Adorno VI", "adorno_vi");
        addSoundToMap("Adorno VII", "adorno_vii");
        addSoundToMap("Adorno VIII", "adorno_viii");
        addSoundToMap("Adorno X", "adorno_x");
        addSoundToMap("Adventure", "adventure");
        addSoundToMap("Agents of Keli", "agents_of_keli");
        addSoundToMap("Airut Ambush", "airut_ambush");
        addSoundToMap("Al Kharid", "al_kharid");
        addSoundToMap("All for the Pest", "all_for_the_pest");
        addSoundToMap("Alls Fairy in Love and War", "alls_fairy_in_love_and_war");
        addSoundToMap("Alone", "alone");
        addSoundToMap("Alpha Omega", "alpha_omega");
        addSoundToMap("Altar Ego", "altar_ego");
        addSoundToMap("Alternative Root", "alternative_root");
        addSoundToMap("Always on my Rind", "always_on_my_rind");
        addSoundToMap("Amascut the Devourer", "amascut_the_devourer");
        addSoundToMap("Ambient Jungle", "ambient_jungle");
        addSoundToMap("Aminishi Adventure", "aminishi_adventure");
        addSoundToMap("Among Tirannwn Trees", "among_tirannwn_trees");
        addSoundToMap("Amor Fati", "amor_fati");
        addSoundToMap("An Easter United", "an_easter_united");
        addSoundToMap("An Echo throughout Time", "an_echo_throughout_time");
        addSoundToMap("Anachronia Encounter", "anachronia_encounter");
        addSoundToMap("Ancestral Wisdom", "ancestral_wisdom");
        addSoundToMap("Angel of Death (Prelude)", "angel_of_death_prelude");
        addSoundToMap("Angel of Death", "angel_of_death");
        addSoundToMap("Anima", "anima");
        addSoundToMap("Animal Apogee", "animal_apogee");
        addSoundToMap("Anywhere", "anywhere");
        addSoundToMap("Aquarium", "aquarium");
        addSoundToMap("Arabian", "arabian");
        addSoundToMap("Arabian2", "arabian2");
        addSoundToMap("Arabian3", "arabian3");
        addSoundToMap("Arabique", "arabique");
        addSoundToMap("Arboretum", "arboretum");
        addSoundToMap("Archaeology Theme", "archaeology_theme");
        addSoundToMap("Architect of War", "architect_of_war");
        addSoundToMap("Ardougne Ago", "ardougne_ago");
        addSoundToMap("Arise Hero", "arise_hero");
        addSoundToMap("Arise Legend", "arise_legend");
        addSoundToMap("Arma Gonna Get You", "arma_gonna_get_you");
        addSoundToMap("Armadyl Alliance", "armadyl_alliance");
        addSoundToMap("Armageddon", "armageddon");
        addSoundToMap("Army of Darkness", "army_of_darkness");
        addSoundToMap("Arrival", "arrival");
        addSoundToMap("Artistry", "artistry");
        addSoundToMap("As Fete Would Have It", "as_fete_would_have_it");
        addSoundToMap("As Rum Can Be", "as_rum_can_be");
        addSoundToMap("Assault and Battery", "assault_and_battery");
        addSoundToMap("Astea Frostweb", "astea_frostweb");
        addSoundToMap("Astral Conflict", "astral_conflict");
        addSoundToMap("Attack I", "attack_i");
        addSoundToMap("Attack II", "attack_ii");
        addSoundToMap("Attack III", "attack_iii");
        addSoundToMap("Attack IV", "attack_iv");
        addSoundToMap("Attack V", "attack_v");
        addSoundToMap("Attack VI", "attack_vi");
        addSoundToMap("Attention", "attention");
        addSoundToMap("Autumn Breeze", "autumn_breeze");
        addSoundToMap("Autumn Voyage", "autumn_voyage");
        addSoundToMap("Awoken", "awoken");
        addSoundToMap("Aye Car Rum Ba", "aye_car_rum_ba");
        addSoundToMap("Aztec", "aztec");
        addSoundToMap("Back to Life", "back_to_life");
        addSoundToMap("Back to the Freezer", "back_to_the_freezer");
        addSoundToMap("Background", "background");
        addSoundToMap("Bad Idea", "bad_idea");
        addSoundToMap("Ballak the Pummeller", "ballak_the_pummeller");
        addSoundToMap("Ballad of Enchantment", "ballad_of_enchantment");
        addSoundToMap("Ballad of the Basilisk", "ballad_of_the_basilisk");
        addSoundToMap("Bandit Camp", "bandit_camp");
        addSoundToMap("Bandos Battalion", "bandos_battalion");
        addSoundToMap("Bandosian Tournament", "bandosian_tournament");
        addSoundToMap("Bane of Summer", "bane_of_summer");
        addSoundToMap("Barb Wire", "barb_wire");
        addSoundToMap("Barbarianism", "barbarianism");
        addSoundToMap("Barking Mad", "barking_mad");
        addSoundToMap("Baroque II", "baroque_ii");
        addSoundToMap("Baroque", "baroque");
        addSoundToMap("Bathypelagic", "bathypelagic");
        addSoundToMap("Battered Soul", "battered_soul");
        addSoundToMap("Battle of Souls", "battle_of_souls");
        addSoundToMap("Battlefield I", "battlefield_i");
        addSoundToMap("Battlefield II", "battlefield_ii");
        addSoundToMap("Baxtorians Hollow", "baxtorians_hollow");
        addSoundToMap("Beast of the Undercurrents", "beast_of_the_undercurrents");
        addSoundToMap("Beastmaster Durzag", "beastmaster_durzag");
        addSoundToMap("Beasts Of Anachronia", "beasts_of_anachronia");
        addSoundToMap("Beetle Juice", "beetle_juice");
        addSoundToMap("Belly of the Beast", "belly_of_the_beast");
        addSoundToMap("Beneath the House", "beneath_the_house");
        addSoundToMap("Better Get Kraken", "better_get_kraken");
        addSoundToMap("Beyond the Storm Wall", "beyond_the_storm_wall");
        addSoundToMap("Beyond Times Reach", "beyond_times_reach");
        addSoundToMap("Beyond", "beyond");
        addSoundToMap("Big Chords", "big_chords");
        addSoundToMap("Bird of Prey", "bird_of_prey");
        addSoundToMap("Bish Bash Bosh", "bish_bash_bosh");
        addSoundToMap("Bittersweet Bunny", "bittersweet_bunny");
        addSoundToMap("Black of Knight", "black_of_knight");
        addSoundToMap("Black Zabeth", "black_zabeth");
        addSoundToMap("Blackstone Scales", "blackstone_scales");
        addSoundToMap("Blackstone Shadows", "blackstone_shadows");
        addSoundToMap("Blackstone Summons", "blackstone_summons");
        addSoundToMap("Blink", "blink");
        addSoundToMap("Blistering Barnacles", "blistering_barnacles");
        addSoundToMap("Blood Hunt", "blood_hunt");
        addSoundToMap("Bloodbath", "bloodbath");
        addSoundToMap("Bloody Foundation", "bloody_foundation");
        addSoundToMap("Blue Wizards", "blue_wizards");
        addSoundToMap("Body Parts", "body_parts");
        addSoundToMap("Body Talk", "body_talk");
        addSoundToMap("Bolries Diary", "bolries_diary");
        addSoundToMap("Bone Dance", "bone_dance");
        addSoundToMap("Bone Dry", "bone_dry");
        addSoundToMap("Book of A Thousand Songs", "book_of_a_thousand_songs");
        addSoundToMap("Book of Spells", "book_of_spells");
        addSoundToMap("Borderland", "borderland");
        addSoundToMap("Born to Do This", "born_to_do_this");
        addSoundToMap("Boulder and Brighter", "boulder_and_brighter");
        addSoundToMap("Bounty Hunter Level 1", "bounty_hunter_level_1");
        addSoundToMap("Bounty Hunter Level 2", "bounty_hunter_level_2");
        addSoundToMap("Bounty Hunter Level 3", "bounty_hunter_level_3");
        addSoundToMap("Bounty", "bounty");
        addSoundToMap("Brain Battle", "brain_battle");
        addSoundToMap("Breaking and Entering", "breaking_and_entering");
        addSoundToMap("Breaking In", "breaking_in");
        addSoundToMap("Breeze", "breeze");
        addSoundToMap("Brew Hoo Hoo", "brew_hoo_hoo");
        addSoundToMap("Brimstails Scales", "brimstails_scales");
        addSoundToMap("Broken Land", "broken_land");
        addSoundToMap("Bubble and Squeak", "bubble_and_squeak");
        addSoundToMap("Building a Better Future", "building_a_better_future");
        addSoundToMap("Bulwark Beast", "bulwark_beast");
        addSoundToMap("Buried in Time", "buried_in_time");
        addSoundToMap("Burthorpe Danger", "burthorpe_danger");
        addSoundToMap("Burthorpe Dilemma", "burthorpe_dilemma");
        addSoundToMap("Burthorpe Dreams", "burthorpe_dreams");
        addSoundToMap("Burthorpe Drummer", "burthorpe_drummer");
        addSoundToMap("Burthorpe Duty", "burthorpe_duty");
        addSoundToMap("Busy Night", "busy_night");
        addSoundToMap("But We Can Fight", "but_we_can_fight");
        addSoundToMap("Cabin Fever", "cabin_fever");
        addSoundToMap("Cage Against the Machine", "cage_against_the_machine");
        addSoundToMap("Caged Guardian", "caged_guardian");
        addSoundToMap("Call to Seiryu", "call_to_seiryu");
        addSoundToMap("Calm Before the Storm", "calm_before_the_storm");
        addSoundToMap("Camelot", "camelot");
        addSoundToMap("Canon in C", "canon_in_c");
        addSoundToMap("Carnillean Rising", "carnillean_rising");
        addSoundToMap("Castle Wars", "castle_wars");
        addSoundToMap("Castle Warz", "castle_warz");
        addSoundToMap("Cataclysm", "cataclysm");
        addSoundToMap("Catacombs and Tombs", "catacombs_and_tombs");
        addSoundToMap("Catch Me If You Can", "catch_me_if_you_can");
        addSoundToMap("Cave Background", "cave_background");
        addSoundToMap("Cave of Beasts", "cave_of_beasts");
        addSoundToMap("Cave of the Goblins", "cave_of_the_goblins");
        addSoundToMap("Cavern", "cavern");
        addSoundToMap("Cavernous Mythology", "cavernous_mythology");
        addSoundToMap("Cellar Song", "cellar_song");
        addSoundToMap("Chain of Command", "chain_of_command");
        addSoundToMap("Chain Reaction", "chain_reaction");
        addSoundToMap("Chamber of Guthix", "chamber_of_guthix");
        addSoundToMap("Chamber of Zaros", "chamber_of_zaros");
        addSoundToMap("Chamber", "chamber");
        addSoundToMap("Champions of Sliske", "champions_of_sliske");
        addSoundToMap("Chaos of Corruption", "chaos_of_corruption");
        addSoundToMap("Chaos Theory", "chaos_theory");
        addSoundToMap("Chaotic Cookery", "chaotic_cookery");
        addSoundToMap("Charmin Farmin", "charmin_farmin");
        addSoundToMap("Charred Remains", "charred_remains");
        addSoundToMap("Chasm Desecrated", "chasm_desecrated");
        addSoundToMap("Cheese Roll", "cheese_roll");
        addSoundToMap("Chef Surprize", "chef_surprize");
        addSoundToMap("Chickened Out", "chickened_out");
        addSoundToMap("Chocolate Factory", "chocolate_factory");
        addSoundToMap("Chompy Hunt", "chompy_hunt");
        addSoundToMap("Christmas Caverns", "christmas_caverns");
        addSoundToMap("Circus", "circus");
        addSoundToMap("Citadel I", "citadel_i");
        addSoundToMap("Citadel II", "citadel_ii");
        addSoundToMap("Citadel III", "citadel_iii");
        addSoundToMap("Citadel IV", "citadel_iv");
        addSoundToMap("Citadel IX", "citadel_ix");
        addSoundToMap("Citadel Theme", "citadel_theme");
        addSoundToMap("Citadel V", "citadel_v");
        addSoundToMap("Citadel VI", "citadel_vi");
        addSoundToMap("Citadel VII", "citadel_vii");
        addSoundToMap("Citadel VIII", "citadel_viii");
        addSoundToMap("Citadel X", "citadel_x");
        addSoundToMap("Citadel XI", "citadel_xi");
        addSoundToMap("Citadel XII", "citadel_xii");
        addSoundToMap("Citadel XIII", "citadel_xiii");
        addSoundToMap("Citadel XIV", "citadel_xiv");
        addSoundToMap("Citadel XV", "citadel_xv");
        addSoundToMap("Citadel XVI", "citadel_xvi");
        addSoundToMap("Citharede Requiem", "citharede_requiem");
        addSoundToMap("City of the Dead", "city_of_the_dead");
        addSoundToMap("Clan Wars", "clan_wars");
        addSoundToMap("Claustrophobia", "claustrophobia");
        addSoundToMap("Cliffhanger", "cliffhanger");
        addSoundToMap("Close Quarters", "close_quarters");
        addSoundToMap("Coleoptera", "coleoptera");
        addSoundToMap("Colonel Grimsson", "colonel_grimsson");
        addSoundToMap("Command Centre", "command_centre");
        addSoundToMap("Competition", "competition");
        addSoundToMap("Complication", "complication");
        addSoundToMap("Confrontation", "confrontation");
        addSoundToMap("Conspiracy Part 1", "conspiracy_part_1");
        addSoundToMap("Conspiracy Part 2", "conspiracy_part_2");
        addSoundToMap("Construct", "construct");
        addSoundToMap("Construction Destruction", "construction_destruction");
        addSoundToMap("Contemplation", "contemplation");
        addSoundToMap("Contest", "contest");
        addSoundToMap("Cool for Ali Cats", "cool_for_ali_cats");
        addSoundToMap("Copris Lunaris", "copris_lunaris");
        addSoundToMap("Corporal Punishment", "corporal_punishment");
        addSoundToMap("Corporate Callousness", "corporate_callousness");
        addSoundToMap("Corridors of Power", "corridors_of_power");
        addSoundToMap("Corruption Slayer", "corruption_slayer");
        addSoundToMap("Courage", "courage");
        addSoundToMap("Creation", "creation");
        addSoundToMap("Creature Cruelty", "creature_cruelty");
        addSoundToMap("Creepy", "creepy");
        addSoundToMap("Crystal Castle", "crystal_castle");
        addSoundToMap("Crystal Cave", "crystal_cave");
        addSoundToMap("Crystal Sword", "crystal_sword");
        addSoundToMap("Cursed Crypt", "cursed_crypt");
        addSoundToMap("Cursed", "cursed");
        addSoundToMap("Cyclosis Shuffle", "cyclosis_shuffle");
        addSoundToMap("Daemonheim Entrance", "daemonheim_entrance");
        addSoundToMap("Daemonheim Fremenniks", "daemonheim_fremenniks");
        addSoundToMap("Dagannoth Dawn", "dagannoth_dawn");
        addSoundToMap("Dance of Death", "dance_of_death");
        addSoundToMap("Dance of the Sphinx", "dance_of_the_sphinx");
        addSoundToMap("Dance of the Undead", "dance_of_the_undead");
        addSoundToMap("Dangerous Logic", "dangerous_logic");
        addSoundToMap("Dangerous Road", "dangerous_road");
        addSoundToMap("Dangerous Way", "dangerous_way");
        addSoundToMap("Dangerous", "dangerous");
        addSoundToMap("Dark", "dark");
        addSoundToMap("Darker Threads", "darker_threads");
        addSoundToMap("Darkmeyer", "darkmeyer");
        addSoundToMap("Darkness in Misthalin", "darkness_in_misthalin");
        addSoundToMap("Darkness", "darkness");
        addSoundToMap("Davy Joness Locker", "davy_joness_locker");
        addSoundToMap("Dawn of War", "dawn_of_war");
        addSoundToMap("DCII Mash-up (Infinity Mix)", "dcii_mashup_infinity_mix");
        addSoundToMap("Dead and Buried", "dead_and_buried");
        addSoundToMap("Dead Can Dance", "dead_can_dance");
        addSoundToMap("Dead Quiet", "dead_quiet");
        addSoundToMap("Deadlands", "deadlands");
        addSoundToMap("Deadliest Catch", "deadliest_catch");
        addSoundToMap("Death", "death");
        addSoundToMap("Deconstruct", "deconstruct");
        addSoundToMap("Deep Down", "deep_down");
        addSoundToMap("Deep Sea Fishing", "deep_sea_fishing");
        addSoundToMap("Deep Wildy", "deep_wildy");
        addSoundToMap("Defenders of Guthix I", "defenders_of_guthix_i");
        addSoundToMap("Defenders of Guthix II", "defenders_of_guthix_ii");
        addSoundToMap("Demise of the Dorgeshuun", "demise_of_the_dorgeshuun");
        addSoundToMap("Desert Heat", "desert_heat");
        addSoundToMap("Desert Island Bear", "desert_island_bear");
        addSoundToMap("Desert Smoke", "desert_smoke");
        addSoundToMap("Desert Voyage", "desert_voyage");
        addSoundToMap("Desolate Ruins", "desolate_ruins");
        addSoundToMap("Desolo I", "desolo_i");
        addSoundToMap("Desolo II", "desolo_ii");
        addSoundToMap("Desolo III", "desolo_iii");
        addSoundToMap("Desolo IV", "desolo_iv");
        addSoundToMap("Desolo IX", "desolo_ix");
        addSoundToMap("Desolo V", "desolo_v");
        addSoundToMap("Desolo VI", "desolo_vi");
        addSoundToMap("Desolo VII", "desolo_vii");
        addSoundToMap("Desolo VIII", "desolo_viii");
        addSoundToMap("Desolo X", "desolo_x");
        addSoundToMap("Destiny", "destiny");
        addSoundToMap("Diangos Little Helpers", "diangos_little_helpers");
        addSoundToMap("Dillo-gence is Key", "dillogence_is_key");
        addSoundToMap("Dimension X", "dimension_x");
        addSoundToMap("Dinosaur Slayer", "dinosaur_slayer");
        addSoundToMap("Dip A Toe (instrumental)", "dip_a_toe_instrumental");
        addSoundToMap("Dip A Toe", "dip_a_toe");
        addSoundToMap("Dirge of Drakan", "dirge_of_drakan");
        addSoundToMap("Discover", "discover");
        addSoundToMap("Disorder", "disorder");
        addSoundToMap("Distant Land", "distant_land");
        addSoundToMap("Distillery Hilarity", "distillery_hilarity");
        addSoundToMap("Divine Skinweaver", "divine_skinweaver");
        addSoundToMap("Dogs of War", "dogs_of_war");
        addSoundToMap("Dominion Lobby I", "dominion_lobby_i");
        addSoundToMap("Dominion Lobby II", "dominion_lobby_ii");
        addSoundToMap("Dominion Lobby III", "dominion_lobby_iii");
        addSoundToMap("Dominion Tower I", "dominion_tower_i");
        addSoundToMap("Dominion Tower II", "dominion_tower_ii");
        addSoundToMap("Dominion Tower III", "dominion_tower_iii");
        addSoundToMap("Dominion Tower IV", "dominion_tower_iv");
        addSoundToMap("Dominion Tower V", "dominion_tower_v");
        addSoundToMap("Dont Panic Zanik", "dont_panic_zanik");
        addSoundToMap("Doorways", "doorways");
        addSoundToMap("Dorgeshuun City", "dorgeshuun_city");
        addSoundToMap("Dorgeshuun Deep", "dorgeshuun_deep");
        addSoundToMap("Down and Out", "down_and_out");
        addSoundToMap("Down Below", "down_below");
        addSoundToMap("Down to Earth", "down_to_earth");
        addSoundToMap("Dracopelagic", "dracopelagic");
        addSoundToMap("Dragon Rider", "dragon_rider");
        addSoundToMap("Dragonkin of Old", "dragonkin_of_old");
        addSoundToMap("Dragonkin Theme", "dragonkin_theme");
        addSoundToMap("Dragonkind", "dragonkind");
        addSoundToMap("Dragontooth Island", "dragontooth_island");
        addSoundToMap("Drains and Canals", "drains_and_canals");
        addSoundToMap("Draynor Market", "draynor_market");
        addSoundToMap("Dreadnaut", "dreadnaut");
        addSoundToMap("Dream Theatre", "dream_theatre");
        addSoundToMap("Dream", "dream");
        addSoundToMap("Dreamstate", "dreamstate");
        addSoundToMap("Duel Arena", "duel_arena");
        addSoundToMap("Dune", "dune");
        addSoundToMap("Dunjun", "dunjun");
        addSoundToMap("Duplicity", "duplicity");
        addSoundToMap("Dusk in Yubiusk", "dusk_in_yubiusk");
        addSoundToMap("Dwarf Theme", "dwarf_theme");
        addSoundToMap("Dying Light II", "dying_light_ii");
        addSoundToMap("Dying Light", "dying_light");
        addSoundToMap("Dynasty", "dynasty");
        addSoundToMap("Eagle Peak", "eagle_peak");
        addSoundToMap("Easter Jig", "easter_jig");
        addSoundToMap("Eastern Promise", "eastern_promise");
        addSoundToMap("Echoes of Guthix", "echoes_of_guthix");
        addSoundToMap("Echoes of the Tempest", "echoes_of_the_tempest");
        addSoundToMap("Egypt", "egypt");
        addSoundToMap("Elder Daughter", "elder_daughter");
        addSoundToMap("Elder Fury", "elder_fury");
        addSoundToMap("Electric Storm", "electric_storm");
        addSoundToMap("Elven Blood", "elven_blood");
        addSoundToMap("Elven Bluebell", "elven_bluebell");
        addSoundToMap("Elven Daffodil", "elven_daffodil");
        addSoundToMap("Elven Dhalia", "elven_dhalia");
        addSoundToMap("Elven Elite", "elven_elite");
        addSoundToMap("Elven Heart", "elven_heart");
        addSoundToMap("Elven Holly", "elven_holly");
        addSoundToMap("Elven Lily", "elven_lily");
        addSoundToMap("Elven Mist", "elven_mist");
        addSoundToMap("Elven Mother", "elven_mother");
        addSoundToMap("Elven Nightshade", "elven_nightshade");
        addSoundToMap("Elven Rose", "elven_rose");
        addSoundToMap("Elven Seed", "elven_seed");
        addSoundToMap("Elven Snapegrass", "elven_snapegrass");
        addSoundToMap("Elven Sunlight", "elven_sunlight");
        addSoundToMap("Elven Sunrise", "elven_sunrise");
        addSoundToMap("Elven Sunset", "elven_sunset");
        addSoundToMap("Elven Voice", "elven_voice");
        addSoundToMap("Emotion", "emotion");
        addSoundToMap("Emperor", "emperor");
        addSoundToMap("Empyrean Citadel", "empyrean_citadel");
        addSoundToMap("End Song", "end_song");
        addSoundToMap("Entombed", "entombed");
        addSoundToMap("Epilogue", "epilogue");
        addSoundToMap("Epipelagic", "epipelagic");
        addSoundToMap("Eruption", "eruption");
        addSoundToMap("Escape", "escape");
        addSoundToMap("Espionage", "espionage");
        addSoundToMap("Etcetera", "etcetera");
        addSoundToMap("Eureka", "eureka");
        addSoundToMap("Everlasting Fire", "everlasting_fire");
        addSoundToMap("Everlasting", "everlasting");
        addSoundToMap("Everlight", "everlight");
        addSoundToMap("Everything in its Right Palace", "everything_in_its_right_palace");
        addSoundToMap("Everywhere", "everywhere");
        addSoundToMap("Evil Bobs Island", "evil_bobs_island");
        addSoundToMap("Evil Daves Theme", "evil_daves_theme");
        addSoundToMap("Evil Spirit", "evil_spirit");
        addSoundToMap("Evil", "evil");
        addSoundToMap("Exam Conditions", "exam_conditions");
        addSoundToMap("Exhibit A", "exhibit_a");
        addSoundToMap("Exorcism", "exorcism");
        addSoundToMap("Expanse", "expanse");
        addSoundToMap("Expecting", "expecting");
        addSoundToMap("Expedition", "expedition");
        addSoundToMap("Exposed", "exposed");
        addSoundToMap("Eye for an Eye (instrumental)", "eye_for_an_eye_instrumental");
        addSoundToMap("Eye for an Eye", "eye_for_an_eye");
        addSoundToMap("Eye Spy", "eye_spy");
        addSoundToMap("Face Off", "face_off");
        addSoundToMap("Faces Obscura", "faces_obscura");
        addSoundToMap("Faerie", "faerie");
        addSoundToMap("Faithless", "faithless");
        addSoundToMap("Fanfare", "fanfare");
        addSoundToMap("Fanfare 2", "fanfare2");
        addSoundToMap("Fanfare 3", "fanfare3");
        addSoundToMap("Fangs for the Memory", "fangs_for_the_memory");
        addSoundToMap("Far Away", "far_away");
        addSoundToMap("Fe Fi Fo Fum", "fe_fi_fo_fum");
        addSoundToMap("Fear and Loathing", "fear_and_loathing");
        addSoundToMap("Fenkenstrains Refrain", "fenkenstrains_refrain");
        addSoundToMap("Fern", "fern");
        addSoundToMap("Fight of the Dwarves", "fight_of_the_dwarves");
        addSoundToMap("Fight or Flight", "fight_or_flight");
        addSoundToMap("Fighting and Praying", "fighting_and_praying");
        addSoundToMap("Fighting for Light Part I", "fighting_for_light_part_i");
        addSoundToMap("Fighting for Light Part II", "fighting_for_light_part_ii");
        addSoundToMap("file_names_list", "file_names_list");
        addSoundToMap("Final Destination", "final_destination");
        addSoundToMap("Final Showdown", "final_showdown");
        addSoundToMap("Find My Way", "find_my_way");
        addSoundToMap("Fire and Brimstone", "fire_and_brimstone");
        addSoundToMap("Fishing", "fishing");
        addSoundToMap("Flash Factory", "flash_factory");
        addSoundToMap("Flesh-spoiler Haasghenahk", "fleshspoiler_haasghenahk");
        addSoundToMap("Floating Free", "floating_free");
        addSoundToMap("Flute Salad", "flute_salad");
        addSoundToMap("Food for Thought", "food_for_thought");
        addSoundToMap("Forbidden", "forbidden");
        addSoundToMap("Forest", "forest");
        addSoundToMap("Forever", "forever");
        addSoundToMap("Forgettable Melody", "forgettable_melody");
        addSoundToMap("Forgotten Continent", "forgotten_continent");
        addSoundToMap("Forgotten Orders", "forgotten_orders");
        addSoundToMap("Forgotten", "forgotten");
        addSoundToMap("Formation", "formation");
        addSoundToMap("Fragments of Guthix", "fragments_of_guthix");
        addSoundToMap("Free Death", "free_death");
        addSoundToMap("Freneskae", "freneskae");
        addSoundToMap("Freshwater", "freshwater");
        addSoundToMap("Frogland", "frogland");
        addSoundToMap("Frost Fight", "frost_fight");
        addSoundToMap("Frostbite", "frostbite");
        addSoundToMap("Fruits de Mer", "fruits_de_mer");
        addSoundToMap("Fun of the Fayre", "fun_of_the_fayre");
        addSoundToMap("Funny Bunnies", "funny_bunnies");
        addSoundToMap("Funus Insula", "funus_insula");
        addSoundToMap("Gaal", "gaal");
        addSoundToMap("Gaol", "gaol");
        addSoundToMap("Garden Echo", "garden_echo");
        addSoundToMap("Garden of Autumn", "garden_of_autumn");
        addSoundToMap("Garden of Spring", "garden_of_spring");
        addSoundToMap("Garden of Summer", "garden_of_summer");
        addSoundToMap("Garden of Winter", "garden_of_winter");
        addSoundToMap("Garden", "garden");
        addSoundToMap("Gemstone Dragons", "gemstone_dragons");
        addSoundToMap("Getting on With Things", "getting_on_with_things");
        addSoundToMap("Ghost of Christmas Presents", "ghost_of_christmas_presents");
        addSoundToMap("Give it Your Pest Shot", "give_it_your_pest_shot");
        addSoundToMap("Glacialis I", "glacialis_i");
        addSoundToMap("Glacialis II", "glacialis_ii");
        addSoundToMap("Glacialis III", "glacialis_iii");
        addSoundToMap("Glacialis IV", "glacialis_iv");
        addSoundToMap("Glacialis IX", "glacialis_ix");
        addSoundToMap("Glacialis V", "glacialis_v");
        addSoundToMap("Glacialis VI", "glacialis_vi");
        addSoundToMap("Glacialis VII", "glacialis_vii");
        addSoundToMap("Glacialis VIII", "glacialis_viii");
        addSoundToMap("Glacialis X", "glacialis_x");
        addSoundToMap("Glutton for Nourishment", "glutton_for_nourishment");
        addSoundToMap("Gluttonous Behemoth", "gluttonous_behemoth");
        addSoundToMap("Gnome King", "gnome_king");
        addSoundToMap("Gnome Village I", "gnome_village_i");
        addSoundToMap("Gnome Village II", "gnome_village_ii");
        addSoundToMap("Gnomeball", "gnomeball");
        addSoundToMap("Go with the Flow", "go_with_the_flow");
        addSoundToMap("Goblin Game", "goblin_game");
        addSoundToMap("Goblin Village", "goblin_village");
        addSoundToMap("Godslayer", "godslayer");
        addSoundToMap("Goebie Theme", "goebie_theme");
        addSoundToMap("Golden Touch", "golden_touch");
        addSoundToMap("Gorgon-Zola", "gorgonzola");
        addSoundToMap("Goshima Lament (instrumental)", "goshima_lament_instrumental");
        addSoundToMap("Goshimas Lament", "goshimas_lament");
        addSoundToMap("Grave Parade", "grave_parade");
        addSoundToMap("Gravecreeper", "gravecreeper");
        addSoundToMap("Greatness", "greatness");
        addSoundToMap("Gregorovic", "gregorovic");
        addSoundToMap("Grimly Fiendish", "grimly_fiendish");
        addSoundToMap("Grip of the Gods", "grip_of_the_gods");
        addSoundToMap("Grip of the Talon", "grip_of_the_talon");
        addSoundToMap("Grotto", "grotto");
        addSoundToMap("Ground Scape", "ground_scape");
        addSoundToMap("Grumpy", "grumpy");
        addSoundToMap("Guardian of the Grove mvt.1", "guardian_of_the_grove_mvt1");
        addSoundToMap("Guardian of the Grove mvt.2", "guardian_of_the_grove_mvt2");
        addSoundToMap("Guardian of the Grove mvt.3", "guardian_of_the_grove_mvt3");
        addSoundToMap("Gunnarsgrunn", "gunnarsgrunn");
        addSoundToMap("Guthixs Hunter", "guthixs_hunter");
        addSoundToMap("Guthixs Warning", "guthixs_warning");
        addSoundToMap("H.A.M. Fisted", "ham_fisted");
        addSoundToMap("Hadopelagic", "hadopelagic");
        addSoundToMap("Halloween Party", "halloween_party");
        addSoundToMap("Hallucinations", "hallucinations");
        addSoundToMap("Ham and Seek", "ham_and_seek");
        addSoundToMap("Ham Attack", "ham_attack");
        addSoundToMap("Hanging in the Balance", "hanging_in_the_balance");
        addSoundToMap("HarLakk the Riftsplitter", "harlakk_the_riftsplitter");
        addSoundToMap("Hare-brained Machines", "harebrained_machines");
        addSoundToMap("Harmony", "harmony");
        addSoundToMap("Harmony2", "harmony2");
        addSoundToMap("Haunted Mine", "haunted_mine");
        addSoundToMap("Have a Blast", "have_a_blast");
        addSoundToMap("Have an Ice Day", "have_an_ice_day");
        addSoundToMap("Head to Head", "head_to_head");
        addSoundToMap("Healin Feelin", "healin_feelin");
        addSoundToMap("Heart and Mind", "heart_and_mind");
        addSoundToMap("Hells Bells", "hells_bells");
        addSoundToMap("Helwyrs Hymn", "helwyrs_hymn");
        addSoundToMap("Henceward", "henceward");
        addSoundToMap("Here and There", "here_and_there");
        addSoundToMap("Hermit", "hermit");
        addSoundToMap("Hidden Evils", "hidden_evils");
        addSoundToMap("High Seas", "high_seas");
        addSoundToMap("High Spirits", "high_spirits");
        addSoundToMap("Hobgoblin Geomancer", "hobgoblin_geomancer");
        addSoundToMap("Holiday Parade", "holiday_parade");
        addSoundToMap("Home Sweet Home", "home_sweet_home");
        addSoundToMap("Homescape", "homescape");
        addSoundToMap("Honkytonky Harmony", "honkytonky_harmony");
        addSoundToMap("Honkytonky Medieval", "honkytonky_medieval");
        addSoundToMap("Honkytonky Newbie Melody", "honkytonky_newbie_melody");
        addSoundToMap("Honkytonky Parade", "honkytonky_parade");
        addSoundToMap("Honkytonky Sea Shanty", "honkytonky_sea_shanty");
        addSoundToMap("Hope Devourer", "hope_devourer");
        addSoundToMap("Horizon", "horizon");
        addSoundToMap("Hot n Bothered", "hot_n_bothered");
        addSoundToMap("Howls Floating Workshop", "howls_floating_workshop");
        addSoundToMap("Hunted", "hunted");
        addSoundToMap("Hunting Dragons", "hunting_dragons");
        addSoundToMap("Hydrothanatic", "hydrothanatic");
        addSoundToMap("Hypnotized", "hypnotized");
        addSoundToMap("I Can See You", "i_can_see_you");
        addSoundToMap("Im Counting on You", "im_counting_on_you");
        addSoundToMap("Iban", "iban");
        addSoundToMap("Ice Day for Penguins", "ice_day_for_penguins");
        addSoundToMap("Ice Melody", "ice_melody");
        addSoundToMap("Icthlarins Little Helper", "icthlarins_little_helper");
        addSoundToMap("Icy a Worried Gnome", "icy_a_worried_gnome");
        addSoundToMap("Icy Bones", "icy_bones");
        addSoundToMap("Icy Trouble Ahead", "icy_trouble_ahead");
        addSoundToMap("Illuminating the Past", "illuminating_the_past");
        addSoundToMap("Illusive", "illusive");
        addSoundToMap("Impetuous", "impetuous");
        addSoundToMap("In Between", "in_between");
        addSoundToMap("In Security", "in_security");
        addSoundToMap("In the Brine", "in_the_brine");
        addSoundToMap("In the Clink", "in_the_clink");
        addSoundToMap("In the Manor", "in_the_manor");
        addSoundToMap("In the Pits", "in_the_pits");
        addSoundToMap("Inadequacy", "inadequacy");
        addSoundToMap("Incantation", "incantation");
        addSoundToMap("Incarceration", "incarceration");
        addSoundToMap("Infiltration", "infiltration");
        addSoundToMap("Inner Secret", "inner_secret");
        addSoundToMap("Insect Queen", "insect_queen");
        addSoundToMap("Inspiration", "inspiration");
        addSoundToMap("Into the Abyss", "into_the_abyss");
        addSoundToMap("Intrepid", "intrepid");
        addSoundToMap("Intrigue at Menaphos", "intrigue_at_menaphos");
        addSoundToMap("Invaders Must Die I", "invaders_must_die_i");
        addSoundToMap("Invaders Must Die II", "invaders_must_die_ii");
        addSoundToMap("Invaders Must Die III", "invaders_must_die_iii");
        addSoundToMap("Island Life", "island_life");
        addSoundToMap("Island of the Trolls", "island_of_the_trolls");
        addSoundToMap("Island Rock", "island_rock");
        addSoundToMap("Isle of Everywhere", "isle_of_everywhere");
        addSoundToMap("Itsy Bitsy...", "itsy_bitsy");
        addSoundToMap("Jack Attack", "jack_attack");
        addSoundToMap("Jadinko Jig", "jadinko_jig");
        addSoundToMap("Jailbird", "jailbird");
        addSoundToMap("Jaws of the Dagannoth", "jaws_of_the_dagannoth");
        addSoundToMap("Jester Minute", "jester_minute");
        addSoundToMap("Jiangshi", "jiangshi");
        addSoundToMap("Jolly-R", "jollyr");
        addSoundToMap("Joy of the Hunt", "joy_of_the_hunt");
        addSoundToMap("Judge and Jury", "judge_and_jury");
        addSoundToMap("Jungle Bells", "jungle_bells");
        addSoundToMap("Jungle Community", "jungle_community");
        addSoundToMap("Jungle Hunt", "jungle_hunt");
        addSoundToMap("Jungle Island XMAS", "jungle_island_xmas");
        addSoundToMap("Jungle Island", "jungle_island");
        addSoundToMap("Jungle Troubles", "jungle_troubles");
        addSoundToMap("Jungly 1", "jungly1");
        addSoundToMap("Jungly 2", "jungly2");
        addSoundToMap("Jungly 3", "jungly3");
        addSoundToMap("KalGer the Warmonger", "kalger_the_warmonger");
        addSoundToMap("Karamja Jam", "karamja_jam");
        addSoundToMap("Kerapacs Curse", "kerapacs_curse");
        addSoundToMap("Kerapacs Lair", "kerapacs_lair");
        addSoundToMap("Kethsi", "kethsi");
        addSoundToMap("Kharidian Bustle", "kharidian_bustle");
        addSoundToMap("Kharidian Nights", "kharidian_nights");
        addSoundToMap("King of the Desert", "king_of_the_desert");
        addSoundToMap("Kingdom", "kingdom");
        addSoundToMap("Kneel to Your God", "kneel_to_your_god");
        addSoundToMap("Knightly", "knightly");
        addSoundToMap("Knightmare", "knightmare");
        addSoundToMap("La Mort", "la_mort");
        addSoundToMap("Labyrinth", "labyrinth");
        addSoundToMap("Lair of Kang Admi", "lair_of_kang_admi");
        addSoundToMap("Lair", "lair");
        addSoundToMap("Lament for the Hallowed", "lament_for_the_hallowed");
        addSoundToMap("Lament of Meiyerditch", "lament_of_meiyerditch");
        addSoundToMap("Lament of the Snow Queen", "lament_of_the_snow_queen");
        addSoundToMap("Lament of the Workers", "lament_of_the_workers");
        addSoundToMap("Lament", "lament");
        addSoundToMap("Lamistards Labyrinth", "lamistards_labyrinth");
        addSoundToMap("Land Down Under", "land_down_under");
        addSoundToMap("Land of Snow", "land_of_snow");
        addSoundToMap("Land of the Dwarves", "land_of_the_dwarves");
        addSoundToMap("Landlubber", "landlubber");
        addSoundToMap("Laniakeas Journey", "laniakeas_journey");
        addSoundToMap("Last Stand", "last_stand");
        addSoundToMap("Lasting", "lasting");
        addSoundToMap("Latent Menace", "latent_menace");
        addSoundToMap("Lava Falls", "lava_falls");
        addSoundToMap("Lazy Wabbit", "lazy_wabbit");
        addSoundToMap("Legend", "legend");
        addSoundToMap("Legion", "legion");
        addSoundToMap("Lexicus Runewright", "lexicus_runewright");
        addSoundToMap("Life Altaring", "life_altaring");
        addSoundToMap("Life Is Good", "life_is_good");
        addSoundToMap("Lifes a Beach", "lifes_a_beach");
        addSoundToMap("Lighthouse", "lighthouse");
        addSoundToMap("Lightwalk", "lightwalk");
        addSoundToMap("Little Cave of Horrors", "little_cave_of_horrors");
        addSoundToMap("Little Rascal", "little_rascal");
        addSoundToMap("Living Rock", "living_rock");
        addSoundToMap("Logical Progression", "logical_progression");
        addSoundToMap("Lonesome", "lonesome");
        addSoundToMap("Long Ago", "long_ago");
        addSoundToMap("Long Road", "long_road");
        addSoundToMap("Long Way Home", "long_way_home");
        addSoundToMap("Looking Back", "looking_back");
        addSoundToMap("Lords and Ladies", "lords_and_ladies");
        addSoundToMap("Lore and Order", "lore_and_order");
        addSoundToMap("Lortnoc Tsep", "lortnoc_tsep");
        addSoundToMap("Lost Soul", "lost_soul");
        addSoundToMap("Lost Souls", "lost_souls");
        addSoundToMap("Love and Hate", "love_and_hate");
        addSoundToMap("Love Bites", "love_bites");
        addSoundToMap("Love Lost", "love_lost");
        addSoundToMap("Love Story", "love_story");
        addSoundToMap("Lullaby", "lullaby");
        addSoundToMap("Luminescent Icefiend", "luminescent_icefiend");
        addSoundToMap("Machines of War", "machines_of_war");
        addSoundToMap("Mad Eadgar", "mad_eadgar");
        addSoundToMap("Mage Arena", "mage_arena");
        addSoundToMap("Magic and Mystery", "magic_and_mystery");
        addSoundToMap("Magic Dance", "magic_dance");
        addSoundToMap("Magic Magic Magic", "magic_magic_magic");
        addSoundToMap("Magical Journey", "magical_journey");
        addSoundToMap("Maiasaura", "maiasaura");
        addSoundToMap("Major Miner", "major_miner");
        addSoundToMap("Make Ends Meet", "make_ends_meet");
        addSoundToMap("Making Waves", "making_waves");
        addSoundToMap("Malady", "malady");
        addSoundToMap("Mantle Depths", "mantle_depths");
        addSoundToMap("March of the Zyclops", "march_of_the_zyclops");
        addSoundToMap("March", "march");
        addSoundToMap("Marooned", "marooned");
        addSoundToMap("Marzipan", "marzipan");
        addSoundToMap("Masquerade", "masquerade");
        addSoundToMap("Master of Light", "master_of_light");
        addSoundToMap("Mastermindless", "mastermindless");
        addSoundToMap("Masuta the Ascended", "masuta_the_ascended");
        addSoundToMap("Mausoleum", "mausoleum");
        addSoundToMap("Max Reidneer Variations", "max_reidneer_variations");
        addSoundToMap("Meddling Kids", "meddling_kids");
        addSoundToMap("Medi-Evil", "medievil");
        addSoundToMap("Medieval II", "medieval_ii");
        addSoundToMap("Medieval", "medieval");
        addSoundToMap("Megans Tale", "megans_tale");
        addSoundToMap("Mellow", "mellow");
        addSoundToMap("Melodrama", "melodrama");
        addSoundToMap("Melzars Maze", "melzars_maze");
        addSoundToMap("Memories From The Grove", "memories_from_the_grove");
        addSoundToMap("Memories of Guthix", "memories_of_guthix");
        addSoundToMap("Memories of Keldagrim", "memories_of_keldagrim");
        addSoundToMap("Meridian", "meridian");
        addSoundToMap("Mesopelagic", "mesopelagic");
        addSoundToMap("Metalwork", "metalwork");
        addSoundToMap("Method of Madness", "method_of_madness");
        addSoundToMap("Miles Away", "miles_away");
        addSoundToMap("Mind Over Matter", "mind_over_matter");
        addSoundToMap("Mindful", "mindful");
        addSoundToMap("Miracle Dance", "miracle_dance");
        addSoundToMap("Mirage", "mirage");
        addSoundToMap("Misadventure", "misadventure");
        addSoundToMap("Miscellania", "miscellania");
        addSoundToMap("Misthalin Mood I", "misthalin_mood_i");
        addSoundToMap("Misthalin Mood II", "misthalin_mood_ii");
        addSoundToMap("Misthalin Mood III", "misthalin_mood_iii");
        addSoundToMap("Moais Lament", "moais_lament");
        addSoundToMap("Mobilising Armies", "mobilising_armies");
        addSoundToMap("Monarch Waltz", "monarch_waltz");
        addSoundToMap("Money-Go-Round", "moneygoround");
        addSoundToMap("Monkey Madness", "monkey_madness");
        addSoundToMap("Monkey Misadventures", "monkey_misadventures");
        addSoundToMap("Monkey See Monkey Do", "monkey_see_monkey_do");
        addSoundToMap("Monster Melee", "monster_melee");
        addSoundToMap("Moody", "moody");
        addSoundToMap("Moral Maze II", "moral_maze_ii");
        addSoundToMap("Moral Maze", "moral_maze");
        addSoundToMap("More Than a Mouthful II", "more_than_a_mouthful_ii");
        addSoundToMap("More Than a Mouthful", "more_than_a_mouthful");
        addSoundToMap("Morytania", "morytania");
        addSoundToMap("Mos Ayes Le", "mos_ayes_le");
        addSoundToMap("Mouse Trap", "mouse_trap");
        addSoundToMap("Ms Granny Potterington", "ms_granny_potterington");
        addSoundToMap("Mudskipper Calliope", "mudskipper_calliope");
        addSoundToMap("Mudskipper Melody", "mudskipper_melody");
        addSoundToMap("Mutant Medley", "mutant_medley");
        addSoundToMap("My Arms Journey", "my_arms_journey");
        addSoundToMap("My Domain", "my_domain");
        addSoundToMap("Mystery Revealed", "mystery_revealed");
        addSoundToMap("Narnodes Theme", "narnodes_theme");
        addSoundToMap("Natural Selection", "natural_selection");
        addSoundToMap("Natural", "natural");
        addSoundToMap("Necrolord", "necrolord");
        addSoundToMap("Neverland", "neverland");
        addSoundToMap("Newbie Melody (Boss)", "newbie_melody_boss");
        addSoundToMap("Newbie Melody (original)", "newbie_melody_original");
        addSoundToMap("Newbie Melody (underwater)", "newbie_melody_underwater");
        addSoundToMap("Newbie Melody", "newbie_melody");
        addSoundToMap("Night of the Vampyre", "night_of_the_vampyre");
        addSoundToMap("Night-gazer Khighorahk", "nightgazer_khighorahk");
        addSoundToMap("Nightfall", "nightfall");
        addSoundToMap("Nightmare at the Cradle", "nightmare_at_the_cradle");
        addSoundToMap("No Way Out", "no_way_out");
        addSoundToMap("Nomad", "nomad");
        addSoundToMap("Non Compos Mentis", "non_compos_mentis");
        addSoundToMap("Norse Code", "norse_code");
        addSoundToMap("Novtumberfest", "novtumberfest");
        addSoundToMap("Null and Void", "null_and_void");
        addSoundToMap("Oasis", "oasis");
        addSoundToMap("Occulo I", "occulo_i");
        addSoundToMap("Occulo II", "occulo_ii");
        addSoundToMap("Occulo III", "occulo_iii");
        addSoundToMap("Occulo IV", "occulo_iv");
        addSoundToMap("Occulo IX", "occulo_ix");
        addSoundToMap("Occulo V", "occulo_v");
        addSoundToMap("Occulo VI", "occulo_vi");
        addSoundToMap("Occulo VII", "occulo_vii");
        addSoundToMap("Occulo VIII", "occulo_viii");
        addSoundToMap("Occulo X", "occulo_x");
        addSoundToMap("Ogre the Top", "ogre_the_top");
        addSoundToMap("On Carpets Wings", "on_carpets_wings");
        addSoundToMap("On Distant Shores", "on_distant_shores");
        addSoundToMap("On Safer Ground", "on_safer_ground");
        addSoundToMap("On the High Ropes", "on_the_high_ropes");
        addSoundToMap("On the Run", "on_the_run");
        addSoundToMap("On the Up", "on_the_up");
        addSoundToMap("On the Wing", "on_the_wing");
        addSoundToMap("On the Wings of Air", "on_the_wings_of_air");
        addSoundToMap("One Voice (instrumental)", "one_voice_instrumental");
        addSoundToMap("One Voice", "one_voice");
        addSoundToMap("Only a King", "only_a_king");
        addSoundToMap("Oriental", "oriental");
        addSoundToMap("Osmans Fable", "osmans_fable");
        addSoundToMap("Out of Control", "out_of_control");
        addSoundToMap("Out of the Deep", "out_of_the_deep");
        addSoundToMap("Over to Nardah", "over_to_nardah");
        addSoundToMap("Overpass", "overpass");
        addSoundToMap("Overture", "overture");
        addSoundToMap("Palace Above", "palace_above");
        addSoundToMap("Palace", "palace");
        addSoundToMap("Parade", "parade");
        addSoundToMap("Path of Peril", "path_of_peril");
        addSoundToMap("Pathways", "pathways");
        addSoundToMap("Penguin Possible", "penguin_possible");
        addSoundToMap("Penguin Prison", "penguin_prison");
        addSoundToMap("Pest Control", "pest_control");
        addSoundToMap("Pharaohs Tomb", "pharaohs_tomb");
        addSoundToMap("Pharaohs Trouble", "pharaohs_trouble");
        addSoundToMap("Phasmatys", "phasmatys");
        addSoundToMap("Pheasant Peasant", "pheasant_peasant");
        addSoundToMap("Philipes Bane", "philipes_bane");
        addSoundToMap("Pinball Wizard", "pinball_wizard");
        addSoundToMap("Pirates of Penance", "pirates_of_penance");
        addSoundToMap("Pirates of Peril", "pirates_of_peril");
        addSoundToMap("Plane-freezer Lakhrahnaz", "planefreezer_lakhrahnaz");
        addSoundToMap("Poison Dreams", "poison_dreams");
        addSoundToMap("Poles Apart", "poles_apart");
        addSoundToMap("Precarious Void", "precarious_void");
        addSoundToMap("Prime Time", "prime_time");
        addSoundToMap("Principality", "principality");
        addSoundToMap("Queen Black Dragon", "queen_black_dragon");
        addSoundToMap("Quest", "quest");
        addSoundToMap("Quicksand", "quicksand");
        addSoundToMap("Rage of the Red Axe", "rage_of_the_red_axe");
        addSoundToMap("RAM upgrade", "ram_upgrade");
        addSoundToMap("Rammernaut", "rammernaut");
        addSoundToMap("Rat a Tat Tat", "rat_a_tat_tat");
        addSoundToMap("Rat Hunt", "rat_hunt");
        addSoundToMap("Ready for Battle", "ready_for_battle");
        addSoundToMap("Reconstruct", "reconstruct");
        addSoundToMap("Red Axe Retribution", "red_axe_retribution");
        addSoundToMap("Regal Tremors", "regal_tremors");
        addSoundToMap("Regal", "regal");
        addSoundToMap("Reggae", "reggae");
        addSoundToMap("Reggae2", "reggae2");
        addSoundToMap("Rellekka", "rellekka");
        addSoundToMap("Remnants", "remnants");
        addSoundToMap("Requiem Rehearsal", "requiem_rehearsal");
        addSoundToMap("Rest for the Weary", "rest_for_the_weary");
        addSoundToMap("Return of Lucien", "return_of_lucien");
        addSoundToMap("Reunion", "reunion");
        addSoundToMap("Right of Conquest", "right_of_conquest");
        addSoundToMap("Right on Track", "right_on_track");
        addSoundToMap("Righteousness", "righteousness");
        addSoundToMap("Rising Damp", "rising_damp");
        addSoundToMap("Riverside", "riverside");
        addSoundToMap("Roc and Roll", "roc_and_roll");
        addSoundToMap("Rocky Rescue", "rocky_rescue");
        addSoundToMap("Roll the Bones", "roll_the_bones");
        addSoundToMap("Romancing the Crone", "romancing_the_crone");
        addSoundToMap("Romper Chomper", "romper_chomper");
        addSoundToMap("Rooftops", "rooftops");
        addSoundToMap("Root Canal", "root_canal");
        addSoundToMap("Roots and Flutes", "roots_and_flutes");
        addSoundToMap("Royal Rumble", "royal_rumble");
        addSoundToMap("Royale", "royale");
        addSoundToMap("Run Escape", "run_escape");
        addSoundToMap("Rune Essence", "rune_essence");
        addSoundToMap("Runearia", "runearia");
        addSoundToMap("Runebreath", "runebreath");
        addSoundToMap("Runecalm", "runecalm");
        addSoundToMap("Runed Behemoth", "runed_behemoth");
        addSoundToMap("Runefear", "runefear");
        addSoundToMap("Runefire", "runefire");
        addSoundToMap("Runeiverse", "runeiverse");
        addSoundToMap("Runenergy", "runenergy");
        addSoundToMap("runescape-music", "runescapemusic");
        addSoundToMap("Runescar", "runescar");
        addSoundToMap("Runespan", "runespan");
        addSoundToMap("Runesphere", "runesphere");
        addSoundToMap("Runesque", "runesque");
        addSoundToMap("Runetine", "runetine");
        addSoundToMap("Runeward", "runeward");
        addSoundToMap("Runewaste", "runewaste");
        addSoundToMap("Runewrath", "runewrath");
        addSoundToMap("Sad Meadow", "sad_meadow");
        addSoundToMap("Safety in Numbers", "safety_in_numbers");
        addSoundToMap("Saga", "saga");
        addSoundToMap("Sagittare", "sagittare");
        addSoundToMap("Sailing Day", "sailing_day");
        addSoundToMap("Sailors Heart (instrumental)", "sailors_heart_instrumental");
        addSoundToMap("Saltwater", "saltwater");
        addSoundToMap("Sanctum", "sanctum");
        addSoundToMap("Sands of Time", "sands_of_time");
        addSoundToMap("Saradomin Camp", "saradomin_camp");
        addSoundToMap("Saradominists", "saradominists");
        addSoundToMap("Sarcophagus", "sarcophagus");
        addSoundToMap("Sarims Vermin", "sarims_vermin");
        addSoundToMap("Scape Bold Heroic", "scape_bold_heroic");
        addSoundToMap("Scape Bold", "scape_bold");
        addSoundToMap("Scape Cave (underwater)", "scape_cave_underwater");
        addSoundToMap("Scape Cave", "scape_cave");
        addSoundToMap("Scape Dark", "scape_dark");
        addSoundToMap("Scape Hunter", "scape_hunter");
        addSoundToMap("Scape Invention", "scape_invention");
        addSoundToMap("Scape Main", "scape_main");
        addSoundToMap("Scape Melancholy", "scape_melancholy");
        addSoundToMap("Scape Original", "scape_original");
        addSoundToMap("Scape Sad", "scape_sad");
        addSoundToMap("Scape Santa", "scape_santa");
        addSoundToMap("Scape Scared", "scape_scared");
        addSoundToMap("Scape Slow", "scape_slow");
        addSoundToMap("Scape Soft", "scape_soft");
        addSoundToMap("Scape Summon", "scape_summon");
        addSoundToMap("Scape Theme", "scape_theme");
        addSoundToMap("Scape Wild", "scape_wild");
        addSoundToMap("Scarab", "scarab");
        addSoundToMap("Scarabaeoidea", "scarabaeoidea");
        addSoundToMap("Scare or Snare", "scare_or_snare");
        addSoundToMap("Schools Out", "schools_out");
        addSoundToMap("Sea Folk", "sea_folk");
        addSoundToMap("Sea Hear", "sea_hear");
        addSoundToMap("Sea Shanty I", "sea_shanty_i");
        addSoundToMap("Sea Shanty II", "sea_shanty_ii");
        addSoundToMap("Sea Shanty XMAS", "sea_shanty_xmas");
        addSoundToMap("Sea You Late Oar", "sea_you_late_oar");
        addSoundToMap("Seasonal Sports", "seasonal_sports");
        addSoundToMap("Seasons Change", "seasons_change");
        addSoundToMap("Second Harmony", "second_harmony");
        addSoundToMap("Second Vision", "second_vision");
        addSoundToMap("Secrets Interred", "secrets_interred");
        addSoundToMap("Seed of Hope", "seed_of_hope");
        addSoundToMap("Seen and not Herb", "seen_and_not_herb");
        addSoundToMap("Seiryus Deliverance", "seiryus_deliverance");
        addSoundToMap("Serens Plea", "serens_plea");
        addSoundToMap("Serenade", "serenade");
        addSoundToMap("Serene", "serene");
        addSoundToMap("Settlement", "settlement");
        addSoundToMap("Shadow-forger Ihlakhizan", "shadowforger_ihlakhizan");
        addSoundToMap("Shadowland", "shadowland");
        addSoundToMap("Shantay Pass", "shantay_pass");
        addSoundToMap("Shanty Instrumental", "shanty_instrumental");
        addSoundToMap("Shanty-Social Behaviour", "shantysocial_behaviour");
        addSoundToMap("Shaping Up", "shaping_up");
        addSoundToMap("Shattered Worlds I", "shattered_worlds_i");
        addSoundToMap("Shattered Worlds II", "shattered_worlds_ii");
        addSoundToMap("Shattered Worlds III", "shattered_worlds_iii");
        addSoundToMap("Shattered Worlds IV", "shattered_worlds_iv");
        addSoundToMap("Shattered Worlds V", "shattered_worlds_v");
        addSoundToMap("Shattered Worlds VI", "shattered_worlds_vi");
        addSoundToMap("Shattered Worlds VII", "shattered_worlds_vii");
        addSoundToMap("Shifting Tombs", "shifting_tombs");
        addSoundToMap("Shine", "shine");
        addSoundToMap("Shining Spirit", "shining_spirit");
        addSoundToMap("Shining", "shining");
        addSoundToMap("Shipwrecked", "shipwrecked");
        addSoundToMap("Showdown", "showdown");
        addSoundToMap("Sigmunds Showdown", "sigmunds_showdown");
        addSoundToMap("Silent Knight", "silent_knight");
        addSoundToMap("Simian Scuffle", "simian_scuffle");
        addSoundToMap("Skeletal Trio", "skeletal_trio");
        addSoundToMap("Skirmish", "skirmish");
        addSoundToMap("Skullery Jam", "skullery_jam");
        addSoundToMap("Skybound and Sundered", "skybound_and_sundered");
        addSoundToMap("Slain to Waste", "slain_to_waste");
        addSoundToMap("Slice of Silent Movie", "slice_of_silent_movie");
        addSoundToMap("Slice of Station", "slice_of_station");
        addSoundToMap("Sliskes Cellmate", "sliskes_cellmate");
        addSoundToMap("Sliskes Secrets", "sliskes_secrets");
        addSoundToMap("Slither and Thither", "slither_and_thither");
        addSoundToMap("Slug a Bug Ball", "slug_a_bug_ball");
        addSoundToMap("Slug Poison", "slug_poison");
        addSoundToMap("Smorgasbord", "smorgasbord");
        addSoundToMap("Snack Attack", "snack_attack");
        addSoundToMap("Snow Patrol", "snow_patrol");
        addSoundToMap("Snowverload", "snowverload");
        addSoundToMap("Soiled", "soiled");
        addSoundToMap("Sojourn", "sojourn");
        addSoundToMap("Something Fishy", "something_fishy");
        addSoundToMap("Something is Wrong", "something_is_wrong");
        addSoundToMap("Song from the Depths", "song_from_the_depths");
        addSoundToMap("Song of the Furies", "song_of_the_furies");
        addSoundToMap("Soul Wars", "soul_wars");
        addSoundToMap("Soulful", "soulful");
        addSoundToMap("Soundscape", "soundscape");
        addSoundToMap("Spa Bizarre", "spa_bizarre");
        addSoundToMap("Sphinx", "sphinx");
        addSoundToMap("Spirit of Aminishi", "spirit_of_aminishi");
        addSoundToMap("Spirit of Chantli", "spirit_of_chantli");
        addSoundToMap("Spirit", "spirit");
        addSoundToMap("Spirits of Elid", "spirits_of_elid");
        addSoundToMap("Splendour", "splendour");
        addSoundToMap("Spoils of War", "spoils_of_war");
        addSoundToMap("Spooky Jungle", "spooky_jungle");
        addSoundToMap("Spooky", "spooky");
        addSoundToMap("Spooky2", "spooky2");
        addSoundToMap("Spring Song", "spring_song");
        addSoundToMap("Stagnant", "stagnant");
        addSoundToMap("Stand-off", "standoff");
        addSoundToMap("Starlight", "starlight");
        addSoundToMap("Start", "start");
        addSoundToMap("Steady", "steady");
        addSoundToMap("Stealing Creation", "stealing_creation");
        addSoundToMap("Stick Your Ale In", "stick_your_ale_in");
        addSoundToMap("Stick Your Oar In", "stick_your_oar_in");
        addSoundToMap("Sticks and Stones", "sticks_and_stones");
        addSoundToMap("Stillness", "stillness");
        addSoundToMap("Stillwater", "stillwater");
        addSoundToMap("Stomp", "stomp");
        addSoundToMap("Storeroom Shuffle", "storeroom_shuffle");
        addSoundToMap("Storm Brew", "storm_brew");
        addSoundToMap("Stranded", "stranded");
        addSoundToMap("Strange Place", "strange_place");
        addSoundToMap("Stratosphere", "stratosphere");
        addSoundToMap("Strength of Saradomin", "strength_of_saradomin");
        addSoundToMap("Sub Way", "sub_way");
        addSoundToMap("Subdued by the Sand", "subdued_by_the_sand");
        addSoundToMap("Subterranea", "subterranea");
        addSoundToMap("Summer Lovin", "summer_lovin");
        addSoundToMap("Sunburn", "sunburn");
        addSoundToMap("Super Furry Animal", "super_furry_animal");
        addSoundToMap("Superstition", "superstition");
        addSoundToMap("Supreme Champions", "supreme_champions");
        addSoundToMap("Suroks Theme", "suroks_theme");
        addSoundToMap("Suspicious", "suspicious");
        addSoundToMap("T.A.R.D.I.S.", "tardis");
        addSoundToMap("Tables are Turned", "tables_are_turned");
        addSoundToMap("Tale of Keldagrim", "tale_of_keldagrim");
        addSoundToMap("Tale of Waiko (instrumental)", "tale_of_waiko_instrumental");
        addSoundToMap("Tale of Waiko", "tale_of_waiko");
        addSoundToMap("Talking Forest", "talking_forest");
        addSoundToMap("Target", "target");
        addSoundToMap("Taverley Adventure", "taverley_adventure");
        addSoundToMap("Taverley Ambience", "taverley_ambience");
        addSoundToMap("Taverley Dreams", "taverley_dreams");
        addSoundToMap("Taverley Enchantment", "taverley_enchantment");
        addSoundToMap("Taverley Folk", "taverley_folk");
        addSoundToMap("Taverley Frolics", "taverley_frolics");
        addSoundToMap("Taverley Lament", "taverley_lament");
        addSoundToMap("Tears of Guthix", "tears_of_guthix");
        addSoundToMap("Technology", "technology");
        addSoundToMap("Temple Desecrated", "temple_desecrated");
        addSoundToMap("Temple of Guthix I", "temple_of_guthix_i");
        addSoundToMap("Temple of Guthix II", "temple_of_guthix_ii");
        addSoundToMap("Temple of Light", "temple_of_light");
        addSoundToMap("Temple of Tribes", "temple_of_tribes");
        addSoundToMap("Temple", "temple");
        addSoundToMap("Temporal Threads", "temporal_threads");
        addSoundToMap("Terrorbird Tussle", "terrorbird_tussle");
        addSoundToMap("The Abbey", "the_abbey");
        addSoundToMap("The Acolytes Accord", "the_acolytes_accord");
        addSoundToMap("The Adventurer", "the_adventurer");
        addSoundToMap("The Art of Hocus-Pocus", "the_art_of_hocuspocus");
        addSoundToMap("The Azure Caverns", "the_azure_caverns");
        addSoundToMap("The Best is Yeti to Come", "the_best_is_yeti_to_come");
        addSoundToMap("The Brass Is Always Greener", "the_brass_is_always_greener");
        addSoundToMap("The Cave", "the_cave");
        addSoundToMap("The Cellar Dwellers", "the_cellar_dwellers");
        addSoundToMap("The Charos Enigma", "the_charos_enigma");
        addSoundToMap("The Chosen Commander", "the_chosen_commander");
        addSoundToMap("The Chosen", "the_chosen");
        addSoundToMap("The Chozan One", "the_chozan_one");
        addSoundToMap("The Columbarium", "the_columbarium");
        addSoundToMap("The Dance of the Snow Queen", "the_dance_of_the_snow_queen");
        addSoundToMap("The Dark Lord", "the_dark_lord");
        addSoundToMap("The Depths", "the_depths");
        addSoundToMap("The Desert", "the_desert");
        addSoundToMap("The Desolate Isle", "the_desolate_isle");
        addSoundToMap("The Duke", "the_duke");
        addSoundToMap("The Elder Halls", "the_elder_halls");
        addSoundToMap("The Enchanter", "the_enchanter");
        addSoundToMap("The Evil Within", "the_evil_within");
        addSoundToMap("The Factory Floor", "the_factory_floor");
        addSoundToMap("The Fallen Hero", "the_fallen_hero");
        addSoundToMap("The Far Side", "the_far_side");
        addSoundToMap("The Fire Burns", "the_fire_burns");
        addSoundToMap("The Firemakers Theme", "the_firemakers_theme");
        addSoundToMap("The Forgotten City Orthen", "the_forgotten_city_orthen");
        addSoundToMap("The Galleon", "the_galleon");
        addSoundToMap("The Gathering", "the_gathering");
        addSoundToMap("The Genie", "the_genie");
        addSoundToMap("The Golem", "the_golem");
        addSoundToMap("The Gulf Between Us", "the_gulf_between_us");
        addSoundToMap("The Hall of Memories", "the_hall_of_memories");
        addSoundToMap("The Harmony of the Runes", "the_harmony_of_the_runes");
        addSoundToMap("The Heist II", "the_heist_ii");
        addSoundToMap("The Heist", "the_heist");
        addSoundToMap("The Horn of Chill", "the_horn_of_chill");
        addSoundToMap("The Infernal Source", "the_infernal_source");
        addSoundToMap("The Last Pirate", "the_last_pirate");
        addSoundToMap("The Last Shanty", "the_last_shanty");
        addSoundToMap("The Longramble Scramble", "the_longramble_scramble");
        addSoundToMap("The Lord of Vampyrium", "the_lord_of_vampyrium");
        addSoundToMap("The Lost Grove", "the_lost_grove");
        addSoundToMap("The Lost Melody", "the_lost_melody");
        addSoundToMap("The Lost Tribe", "the_lost_tribe");
        addSoundToMap("The Lumbridge Reels", "the_lumbridge_reels");
        addSoundToMap("The Lunar Isle", "the_lunar_isle");
        addSoundToMap("The Mad Mole", "the_mad_mole");
        addSoundToMap("The Magisters Lesson", "the_magisters_lesson");
        addSoundToMap("The Menaphos Folk Singer", "the_menaphos_folk_singer");
        addSoundToMap("The Mentor", "the_mentor");
        addSoundToMap("The Mollusc Menace", "the_mollusc_menace");
        addSoundToMap("The Monsters Below", "the_monsters_below");
        addSoundToMap("The Muspahs Tomb", "the_muspahs_tomb");
        addSoundToMap("The Navigator", "the_navigator");
        addSoundToMap("The Needle", "the_needle");
        addSoundToMap("The Nightmare Continues", "the_nightmare_continues");
        addSoundToMap("The Noble Rodent", "the_noble_rodent");
        addSoundToMap("The Other Side", "the_other_side");
        addSoundToMap("The Pact", "the_pact");
        addSoundToMap("The Pengmersible", "the_pengmersible");
        addSoundToMap("The Phoenix", "the_phoenix");
        addSoundToMap("The Plundered Tomb", "the_plundered_tomb");
        addSoundToMap("The Power of Tears", "the_power_of_tears");
        addSoundToMap("The Price is Wight", "the_price_is_wight");
        addSoundToMap("The Quiz Master", "the_quiz_master");
        addSoundToMap("The Reapers House", "the_reapers_house");
        addSoundToMap("The Records Chamber", "the_records_chamber");
        addSoundToMap("The Rogues Den", "the_rogues_den");
        addSoundToMap("The Route of All Evil", "the_route_of_all_evil");
        addSoundToMap("The Route of the Problem", "the_route_of_the_problem");
        addSoundToMap("The Ruins of Camdozaal", "the_ruins_of_camdozaal");
        addSoundToMap("The Ruler and the Ruled", "the_ruler_and_the_ruled");
        addSoundToMap("The Sacred Steward", "the_sacred_steward");
        addSoundToMap("The Sailors Heart", "the_sailors_heart");
        addSoundToMap("The Seat of Power", "the_seat_of_power");
        addSoundToMap("The Shackled Aberration", "the_shackled_aberration");
        addSoundToMap("The Shackled Serpent", "the_shackled_serpent");
        addSoundToMap("The Shadow", "the_shadow");
        addSoundToMap("The Sight Of Spring", "the_sight_of_spring");
        addSoundToMap("The Slayer", "the_slayer");
        addSoundToMap("The Sound of Guthix", "the_sound_of_guthix");
        addSoundToMap("The Stalker", "the_stalker");
        addSoundToMap("The Star Lodge", "the_star_lodge");
        addSoundToMap("The Tale of Amascut", "the_tale_of_amascut");
        addSoundToMap("The Tale of Crondis", "the_tale_of_crondis");
        addSoundToMap("The Tale of Het", "the_tale_of_het");
        addSoundToMap("The Tale of Jack of Spades", "the_tale_of_jack_of_spades");
        addSoundToMap("The Task at Hand", "the_task_at_hand");
        addSoundToMap("The Terrible Caverns", "the_terrible_caverns");
        addSoundToMap("The Terrible Tower", "the_terrible_tower");
        addSoundToMap("The Terrible Tunnels", "the_terrible_tunnels");
        addSoundToMap("The Throne of Bandos", "the_throne_of_bandos");
        addSoundToMap("The Tower", "the_tower");
        addSoundToMap("The Town", "the_town");
        addSoundToMap("The Trade Parade", "the_trade_parade");
        addSoundToMap("The Twilight Twain", "the_twilight_twain");
        addSoundToMap("The Vacant Abyss", "the_vacant_abyss");
        addSoundToMap("The Void Stares Back", "the_void_stares_back");
        addSoundToMap("The Waiting Game", "the_waiting_game");
        addSoundToMap("The Wrong Path", "the_wrong_path");
        addSoundToMap("Theme", "theme");
        addSoundToMap("There Has Been a Murder", "there_has_been_a_murder");
        addSoundToMap("These Stones", "these_stones");
        addSoundToMap("Thieves Guild I", "thieves_guild_i");
        addSoundToMap("Thieves Guild II", "thieves_guild_ii");
        addSoundToMap("Thieves Guild III", "thieves_guild_iii");
        addSoundToMap("Thieves Guild IV", "thieves_guild_iv");
        addSoundToMap("Thoks Big Adventure", "thoks_big_adventure");
        addSoundToMap("Three Brothers", "three_brothers");
        addSoundToMap("Three Kings", "three_kings");
        addSoundToMap("Three of a Kind", "three_of_a_kind");
        addSoundToMap("Throne of the Demon", "throne_of_the_demon");
        addSoundToMap("Time is the Key", "time_is_the_key");
        addSoundToMap("Time Out", "time_out");
        addSoundToMap("Time to Mine", "time_to_mine");
        addSoundToMap("Time Waits for Snowman", "time_waits_for_snowman");
        addSoundToMap("Tiny Adventure", "tiny_adventure");
        addSoundToMap("Tiptoe", "tiptoe");
        addSoundToMap("Title Fight", "title_fight");
        addSoundToMap("ToKash the Bloodchiller", "tokash_the_bloodchiller");
        addSoundToMap("TokTz-Ket-Ek-Mack", "toktzketekmack");
        addSoundToMap("Tomb Raider", "tomb_raider");
        addSoundToMap("Tomorrow", "tomorrow");
        addSoundToMap("Too Many Cooks...", "too_many_cooks");
        addSoundToMap("Torqueo I", "torqueo_i");
        addSoundToMap("Torqueo II", "torqueo_ii");
        addSoundToMap("Torqueo III", "torqueo_iii");
        addSoundToMap("Torqueo IV", "torqueo_iv");
        addSoundToMap("Torqueo IX", "torqueo_ix");
        addSoundToMap("Torqueo V", "torqueo_v");
        addSoundToMap("Torqueo VI", "torqueo_vi");
        addSoundToMap("Torqueo VII", "torqueo_vii");
        addSoundToMap("Torqueo VIII", "torqueo_viii");
        addSoundToMap("Torqueo X", "torqueo_x");
        addSoundToMap("Tortle Power", "tortle_power");
        addSoundToMap("Tournament", "tournament");
        addSoundToMap("Travellers Tale", "travellers_tale");
        addSoundToMap("Trawler Minor", "trawler_minor");
        addSoundToMap("Trawler", "trawler");
        addSoundToMap("Tree Spirits", "tree_spirits");
        addSoundToMap("Trees Arent Your Friends", "trees_arent_your_friends");
        addSoundToMap("Tremble", "tremble");
        addSoundToMap("Tribal Background", "tribal_background");
        addSoundToMap("Tribal", "tribal");
        addSoundToMap("Tribal 2", "tribal2");
        addSoundToMap("Trick or Treat", "trick_or_treat");
        addSoundToMap("Trinity", "trinity");
        addSoundToMap("Troll Invasion", "troll_invasion");
        addSoundToMap("Tropical Breeze", "tropical_breeze");
        addSoundToMap("Tropical Sneeze", "tropical_sneeze");
        addSoundToMap("Troubadour Dance", "troubadour_dance");
        addSoundToMap("Trouble Brewing", "trouble_brewing");
        addSoundToMap("Troubled Spirit", "troubled_spirit");
        addSoundToMap("Troubled", "troubled");
        addSoundToMap("True or False", "true_or_false");
        addSoundToMap("Tuai Leit", "tuai_leit");
        addSoundToMap("Tune from the Dune", "tune_from_the_dune");
        addSoundToMap("Tuska", "tuska");
        addSoundToMap("Twilight", "twilight");
        addSoundToMap("Tzhaar City I", "tzhaar_city_i");
        addSoundToMap("Tzhaar City II", "tzhaar_city_ii");
        addSoundToMap("Tzhaar City III", "tzhaar_city_iii");
        addSoundToMap("Tzhaar City IV", "tzhaar_city_iv");
        addSoundToMap("Tzhaar City V", "tzhaar_city_v");
        addSoundToMap("Tzhaar Supremacy I", "tzhaar_supremacy_i");
        addSoundToMap("Tzhaar Supremacy II", "tzhaar_supremacy_ii");
        addSoundToMap("Tzhaar Supremacy III", "tzhaar_supremacy_iii");
        addSoundToMap("TzHaar", "tzhaar");
        addSoundToMap("Unavoidable Conflict", "unavoidable_conflict");
        addSoundToMap("Undead Army II", "undead_army_ii");
        addSoundToMap("Undead Army", "undead_army");
        addSoundToMap("Undead Dungeon", "undead_dungeon");
        addSoundToMap("Under the Sand", "under_the_sand");
        addSoundToMap("Underbelly", "underbelly");
        addSoundToMap("Undercity", "undercity");
        addSoundToMap("Undercurrent", "undercurrent");
        addSoundToMap("Underground Pass", "underground_pass");
        addSoundToMap("Underground", "underground");
        addSoundToMap("Understanding", "understanding");
        addSoundToMap("Undying", "undying");
        addSoundToMap("Unholy Cursebearer", "unholy_cursebearer");
        addSoundToMap("Unknown Land", "unknown_land");
        addSoundToMap("Unravelling the Past", "unravelling_the_past");
        addSoundToMap("Untamed Horizons", "untamed_horizons");
        addSoundToMap("Untouchable", "untouchable");
        addSoundToMap("Upcoming", "upcoming");
        addSoundToMap("Upir Likhyi", "upir_likhyi");
        addSoundToMap("Valerios Song", "valerios_song");
        addSoundToMap("Vanescula Fight", "vanescula_fight");
        addSoundToMap("Venomous", "venomous");
        addSoundToMap("Venture", "venture");
        addSoundToMap("Venture2", "venture2");
        addSoundToMap("Victory is Mine", "victory_is_mine");
        addSoundToMap("Village Dance", "village_dance");
        addSoundToMap("Village Fate", "village_fate");
        addSoundToMap("Village Life", "village_life");
        addSoundToMap("Village", "village");
        addSoundToMap("Violets First Adventure", "violets_first_adventure");
        addSoundToMap("Violinsanity", "violinsanity");
        addSoundToMap("Vision", "vision");
        addSoundToMap("Void Knights Theme", "void_knights_theme");
        addSoundToMap("Volcanic Vikings", "volcanic_vikings");
        addSoundToMap("Voodoo Cult", "voodoo_cult");
        addSoundToMap("Vorago", "vorago");
        addSoundToMap("Voyage", "voyage");
        addSoundToMap("Waiting for Battle", "waiting_for_battle");
        addSoundToMap("Waiting for the Hunt", "waiting_for_the_hunt");
        addSoundToMap("Waking Dream", "waking_dream");
        addSoundToMap("Wander Waltz", "wander_waltz");
        addSoundToMap("Wander", "wander");
        addSoundToMap("Warped Gulega", "warped_gulega");
        addSoundToMap("Warrior", "warrior");
        addSoundToMap("Warriors Guild", "warriors_guild");
        addSoundToMap("Waste Defaced", "waste_defaced");
        addSoundToMap("Waterfall II", "waterfall_ii");
        addSoundToMap("Waterfall III", "waterfall_iii");
        addSoundToMap("Waterfall", "waterfall");
        addSoundToMap("Waterlogged", "waterlogged");
        addSoundToMap("Way of the Enchanter", "way_of_the_enchanter");
        addSoundToMap("Wayward", "wayward");
        addSoundToMap("We Are the Fairies", "we_are_the_fairies");
        addSoundToMap("We Menaphites We Fight", "we_menaphites_we_fight");
        addSoundToMap("Weaving", "weaving");
        addSoundToMap("Webbed Feat", "webbed_feat");
        addSoundToMap("Welcome To The Easter Fete", "welcome_to_the_easter_fete");
        addSoundToMap("Well of Voyage", "well_of_voyage");
        addSoundToMap("Wending Through the Willows", "wending_through_the_willows");
        addSoundToMap("Whales Maw", "whales_maw");
        addSoundToMap("What Lies Beneath", "what_lies_beneath");
        addSoundToMap("What We Do", "what_we_do");
        addSoundToMap("Where Eagles Lair", "where_eagles_lair");
        addSoundToMap("While We Sleep", "while_we_sleep");
        addSoundToMap("White Whale (instrumental)", "white_whale_instrumental");
        addSoundToMap("White Whale", "white_whale");
        addSoundToMap("Who Are We To Judge", "who_are_we_to_judge");
        addSoundToMap("Who is Pharaoh (instrumental)", "who_is_pharaoh_instrumental");
        addSoundToMap("Who is the Pharaoh", "who_is_the_pharaoh");
        addSoundToMap("Whooo-Reeka", "whoooreeka");
        addSoundToMap("Wild Isle", "wild_isle");
        addSoundToMap("Wild Side", "wild_side");
        addSoundToMap("Wilderness I", "wilderness_i");
        addSoundToMap("Wilderness II", "wilderness_ii");
        addSoundToMap("Wilderness III", "wilderness_iii");
        addSoundToMap("Wildwood", "wildwood");
        addSoundToMap("Winter Funfare", "winter_funfare");
        addSoundToMap("Winter Workin Night and Day", "winter_workin_night_and_day");
        addSoundToMap("Witching", "witching");
        addSoundToMap("Woe of the Wyvern", "woe_of_the_wyvern");
        addSoundToMap("Wonder", "wonder");
        addSoundToMap("Wonderous", "wonderous");
        addSoundToMap("Woodland", "woodland");
        addSoundToMap("Work While They Play", "work_while_they_play");
        addSoundToMap("Work Work Work", "work_work_work");
        addSoundToMap("Workshop", "workshop");
        addSoundToMap("World-gorger Shukarhazh", "worldgorger_shukarhazh");
        addSoundToMap("Worlds Apart", "worlds_apart");
        addSoundToMap("Worlds", "worlds");
        addSoundToMap("Wrath and Ruin", "wrath_and_ruin");
        addSoundToMap("Wyrds Woe", "wyrds_woe");
        addSoundToMap("Wyrding Way", "wyrding_way");
        addSoundToMap("Xenophobe", "xenophobe");
        addSoundToMap("Yakamaru I", "yakamaru_i");
        addSoundToMap("Yakamaru II", "yakamaru_ii");
        addSoundToMap("Yesteryear", "yesteryear");
        addSoundToMap("YkLagor the Thunderous", "yklagor_the_thunderous");
        addSoundToMap("You Will Know Me", "you_will_know_me");
        addSoundToMap("Yubiusk", "yubiusk");
        addSoundToMap("Zamorak Camp", "zamorak_camp");
        addSoundToMap("Zamorak Zoo", "zamorak_zoo");
        addSoundToMap("Zaniks Theme", "zaniks_theme");
        addSoundToMap("Zaros Returns", "zaros_returns");
        addSoundToMap("Zaros Stirs", "zaros_stirs");
        addSoundToMap("Zaros Zeitgeist", "zaros_zeitgeist");
        addSoundToMap("Zarosian Reprise", "zarosian_reprise");
        addSoundToMap("Zealot", "zealot");
        addSoundToMap("Zogre Dance", "zogre_dance");
        addSoundToMap("Zombie Invasion", "zombie_invasion");
        addSoundToMap("Zombiism", "zombiism");

    }






}
